import { teamNames } from "./teamNames";

export const initialSheduleData = {
  division_1: [
    {
      teamName: teamNames.team_1,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_2,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_3,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_4,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_5,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_6,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_7,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_8,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_9,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_10,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
  ],
  division_2: [
    {
      teamName: teamNames.team_11,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_12,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_13,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_14,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_15,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_16,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_17,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_18,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_19,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_20,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
  ],
  division_3: [
    {
      teamName: teamNames.team_21,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_22,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_23,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_24,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_25,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_26,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_27,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_28,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_29,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_30,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
  ],
};
