import { teamNames } from "./enums/teamNames";

export const initialSheduleData = {
  division_1: [
    {
      teamName: teamNames.Arsenal,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.AtleticoMadrid,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.Barcelona,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.BayernMunich,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.BorussiaDortmund,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.Chelsea,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.InterMilan,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.Juventus,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.Liverpool,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.ManchesterCity,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
  ],
  division_2: [
    {
      teamName: teamNames.ManchesterUnited,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.Milan,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.PSG,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.RealMadrid,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.TottenhamHotspur,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_16,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_17,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_18,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_19,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_20,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
  ],
  division_3: [
    {
      teamName: teamNames.team_21,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_22,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_23,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_24,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_25,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_26,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_27,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_28,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_29,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
    {
      teamName: teamNames.team_30,
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
      strength: 0,
    },
  ],
};
